<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0\appsettings.Development.json" />
    <Content Include="bin\Debug\net8.0\appsettings.json" />
    <Content Include="bin\Debug\net8.0\RestaurantCRM.Web.deps.json" />
    <Content Include="bin\Debug\net8.0\RestaurantCRM.Web.runtimeconfig.json" />
    <Content Include="bin\Debug\net8.0\RestaurantCRM.Web.staticwebassets.endpoints.json" />
    <Content Include="bin\Debug\net8.0\RestaurantCRM.Web.staticwebassets.runtime.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Release\net8.0\" />
    <Folder Include="DTOs\" />
    <Folder Include="Config\" />
    <Folder Include="Shared\" />
    <Folder Include="Services\" />
    <Folder Include="Views\DonHang\" />
    <Folder Include="Views\GioHang\" />
    <Folder Include="Views\KhaoSat\" />
    <Folder Include="Views\PhanHoi\" />
    <Folder Include="Views\TaiKhoan\" />
    <Folder Include="Views\TrangChu\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net8.0\RestaurantCRM.Web.dll" />
    <None Include="bin\Debug\net8.0\RestaurantCRM.Web.exe" />
    <None Include="bin\Debug\net8.0\RestaurantCRM.Web.pdb" />
  </ItemGroup>

</Project>
